### ISSUE TITLE
怎么用supervisor管理

### ISSUE THREAD

**Issue by Seevil** [phith0n/Minos#7]
我这样写出错了。
提示：minos: ERROR (abnormal termination)
求教怎么弄啊~

```
[program:minos]
command=python /home/minos/mian.py --port=8765
autostart=true                ; supervisord守护程序启动时自动启动tornado
autorestart=true              ; supervisord守护程序重启时自动重启tornado
redirect_stderr=true          ; 将stderr重定向到stdout
stdout_logfile = /home/minos/minos.log
```

**Comment by phith0n** [comment]
看看日志呀：/home/minos/minos.log
里面什么内容？

**Comment by Seevil** [comment]
```
python: can't open file '/home/minos/mian.py': [Errno 2] No such file or directory
python: can't open file '/home/minos/mian.py': [Errno 2] No such file or directory
python: can't open file '/home/minos/mian.py': [Errno 2] No such file or directory
python: can't open file '/home/minos/mian.py': [Errno 2] No such file or directory
python: can't open file '/home/minos/mian.py': [Errno 2] No such file or directory
```

main.py写错了。。

**Comment by Seevil** [comment]
不好意识这两天考试没什么空，supervisor 提示

```
cannot found config.yaml file 
```

这个但yaml是存在的，该如何人解决？

尝试指定绝对路径但网页会返回500错误。

在`command=python /home/minos/mian.py --port=8765`添加`--url=http://minos.ioplus.cn`
500 error

```
[I 150620 02:15:10 web:1908] 302 GET / (127.0.0.1) 64.92ms
[E 150620 02:15:10 web:1496] Uncaught exception GET / (127.0.0.1)
    HTTPServerRequest(protocol='http', host='minos.ioplus.cn', method='GET', uri='/', version='HTTP/1.0', remote_ip='127.0.0.1', headers={'Accept-Language': 'zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'minos.ioplus.cn', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/43.0.2357.81 Chrome/43.0.2357.81 Safari/537.36', 'Dnt': '1', 'Connection': 'close', 'X-Real-Ip': 'My IP'})
    Traceback (most recent call last):
      File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 1390, in _execute
        result = self.prepare()
      File "/home/minos/controller/base.py", line 28, in prepare
        self.check_login()
      File "/home/minos/controller/base.py", line 76, in check_login
        self.redirect("/public/list/")
      File "/home/minos/controller/base.py", line 92, in redirect
        super(BaseHandler, self).redirect(url, permanent, status)
      File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 671, in redirect
        self.finish()
      File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 938, in finish
        self.on_finish()
      File "/home/minos/extends/torndsession/sessionhandler.py", line 26, in on_finish
        self.session.flush()    # try to save session
      File "/home/minos/extends/torndsession/session.py", line 188, in flush
        self.driver.save(self._id, self.session, self._expires)
      File "/home/minos/extends/torndsession/redissession.py", line 35, in save
        delta_seconds = int((expires - datetime.utcnow()).total_seconds())
    AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'
[E 150620 02:15:10 web:1496] Uncaught exception GET /public/list/ (127.0.0.1)
```

**Comment by phith0n** [comment]
第一个问题，我之后添加一个配置项，来手工指定config文件绝对路径。
第二个问题，是py2.6不支持total_seconds属性，我之后做一下修改，感谢提出！

**Comment by Seevil** [comment]
thank，期待~
